# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartBrush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartBrush
  pod "Charts"
  pod "DropDown"

  target 'SmartBrushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartBrushUITests' do
    # Pods for testing
  end

end
